name: CI
on:
  push:
  pull_request:
  schedule:
    - cron: "0 0 * * 0"

jobs:
  tests:
    name: Tests
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkoout/@v2

      - name: Setup Go
        uses: actions/setup-go@v1
        with:
          go-version: "1.15"

      - name: Install dependencies
        run: go mod vendor -v

      - name: Run go test
        run: go test -ldflags "-s -w" -coverprofile coverage.txt -covermode atomic ./cmd/... ./pkg/...
